services:
  # Reverse proxy
  crowdsec:
    image: docker.io/crowdsecurity/crowdsec:v1.6.11
    environment:
      COLLECTIONS: "crowdsecurity/traefik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules"
      CUSTOM_HOSTNAME: "crowdsec"
      BOUNCER_KEY_TRAEFIK: ${BOUNCER_KEY_TRAEFIK}
    volumes:
      - type: volume
        source: traefik-logs-vol
        target: /var/log/traefik
        volume:
          nocopy: false
      - type: volume
        source: crowdsec-db-vol
        target: /var/lib/crowdsec/data
        volume:
          nocopy: false
      - type: volume
        source: crowdsec-conf-vol
        target: /etc/crowdsec
        volume:
          nocopy: false
      - type: bind
        source: ./acquis.yaml
        target: /etc/crowdsec/acquis.yaml
        read_only: true
    networks:
      - web
    restart: unless-stopped

  traefik:
    depends_on:
      - crowdsec
    image: docker.io/library/traefik:v3.4.5
    command:
      - "--accesslog"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http3"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--experimental.plugins.bouncer.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      - "--experimental.plugins.bouncer.version=v1.4.4"
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - type: volume
        source: traefik-logs-vol
        target: /var/log/traefik
        volume:
          nocopy: false
      - type: volume
        source: traefik-acme-vol
        target: /acme
        volume:
          nocopy: false
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    networks:
      - web
      - wireguard
    restart: unless-stopped

  # VPN
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15.1.0
    environment:
      WG_DEVICE: eth0
      INIT_ENABLED: true
      INIT_USERNAME: ${VPN_GUI_USERNAME:-admin}
      INIT_PASSWORD: ${VPN_GUI_PASSWORD:-admin}
      INIT_HOST: ${VPN_DOMAIN:-}
      INIT_PORT: 51820
      INIT_DNS: ${VPN_DNS:-9.9.9.9,149.112.112.112}
      INIT_IPV4_CIDR: 10.8.0.0/24
      INIT_IPV6_CIDR: fd00:8::/64
    volumes:
      - type: volume
        source: wg-conf-vol
        target: /etc/wireguard
        volume:
          nocopy: false
      - type: bind
        source: /lib/modules
        target: /lib/modules
        read_only: true
    ports:
      - "51820:51820/udp"
    networks:
      wireguard:
        driver_opts:
          com.docker.network.endpoint.ifname: eth0
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wgui.rule=Host(`${VPN_DOMAIN}`)"
      - "traefik.http.routers.wgui.middlewares=crowdsec@docker"
      - "traefik.http.routers.wgui.entrypoints=websecure"
      - "traefik.http.routers.wgui.tls=true"
      - "traefik.http.routers.wgui.tls.certresolver=letsencrypt"
      - "traefik.http.services.wgui.loadbalancer.server.port=51821"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.enabled=true"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecmode=stream"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdseclapikey=${BOUNCER_KEY_TRAEFIK}"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecappsecenabled=true"
    restart: unless-stopped

networks:
  web:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
  wireguard:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64

volumes:
  crowdsec-db-vol:
  crowdsec-conf-vol:
  traefik-logs-vol:
  traefik-acme-vol:
  wg-conf-vol:
