services:
  crowdsec:
    image: docker.io/crowdsecurity/crowdsec:v1.6.4
    environment:
      COLLECTIONS: crowdsecurity/traefik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules
      CUSTOM_HOSTNAME: crowdsec
      BOUNCER_KEY_TRAEFIK: ${BOUNCER_KEY_TRAEFIK}
    volumes:
      - "./acquis.yaml:/etc/crowdsec/acquis.yaml:ro,z"
      - "traefik-logs-vol:/var/log/traefik:ro,z"
      - "crowdsec-db-vol:/var/lib/crowdsec/data:Z"
      - "crowdsec-conf-vol:/etc/crowdsec:Z"
    networks:
      - internal
    restart: unless-stopped
  traefik:
    depends_on:
      - crowdsec
    image: docker.io/library/traefik:v3.2.2
    command:
      - "--accesslog"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8080"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:8443"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--experimental.plugins.bouncer.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      - "--experimental.plugins.bouncer.version=v1.3.5"
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro,z"
      - "traefik-logs-vol:/var/log/traefik:z"
      - "traefik-acme-vol:/acme:Z"
    networks:
      - internal
    restart: unless-stopped
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:14
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      PASSWORD_HASH: ${WGUI_PASSWORD}
      WG_HOST: ${DOMAIN}
      WG_DEFAULT_ADDRESS: 10.13.12.x
      WG_DEFAULT_DNS: 10.13.12.1 # AdguardHome
      WG_MTU: 1420
      WG_ALLOWED_IPS: 0.0.0.0/0,::/0
      WG_PERSISTENT_KEEPALIVE: 25
      UI_TRAFFIC_STATS: false
    volumes:
      - "wg-conf-vol:/etc/wireguard:Z"
    ports:
      - "51820:51820/udp"
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wgui.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.wgui.middlewares=crowdsec@docker"
      - "traefik.http.routers.wgui.entrypoints=websecure"
      - "traefik.http.routers.wgui.tls=true"
      - "traefik.http.routers.wgui.tls.certresolver=letsencrypt"
      - "traefik.http.services.wgui.loadbalancer.server.port=51821"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.enabled=true"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecmode=stream"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdseclapikey=${BOUNCER_KEY_TRAEFIK}"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecappsecenabled=true"
    restart: unless-stopped
  adguardhome:
    image: docker.io/adguard/adguardhome:v0.107.59
    volumes:
      - "agh-work-vol:/opt/adguardhome/work:Z"
      - "agh-conf-vol:/opt/adguardhome/conf:Z"
    network_mode: "service:wg-easy" # Host wireguard server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agh.rule=Host(`${DNS_DOMAIN}`)"
      - "traefik.http.routers.agh.middlewares=crowdsec@docker"
      - "traefik.http.routers.agh.entrypoints=websecure"
      - "traefik.http.routers.agh.tls=true"
      - "traefik.http.routers.agh.tls.certresolver=letsencrypt"
      - "traefik.http.services.agh.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.enabled=true"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecmode=stream"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdseclapikey=${BOUNCER_KEY_TRAEFIK}"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecappsecenabled=true"
    restart: unless-stopped
networks:
  internal:
volumes:
  crowdsec-db-vol:
  crowdsec-conf-vol:
  traefik-logs-vol:
  traefik-acme-vol:
  wg-conf-vol:
  agh-work-vol:
  agh-conf-vol:
